// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/createApi": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "创建基础api",
                "parameters": [
                    {
                        "description": "api路径, api中文描述, api组, 方法",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/deleteApi": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "删除api",
                "parameters": [
                    {
                        "description": "ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/getAllApis": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "获取所有的Api 不分页",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/getApiById": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "根据id获取api",
                "parameters": [
                    {
                        "description": "根据id获取api",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/getApiList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "分页获取API列表",
                "parameters": [
                    {
                        "description": "分页获取API列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SearchApiParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/updateApi": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "创建基础api",
                "parameters": [
                    {
                        "description": "api路径, api中文描述, api组, 方法",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/copyAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "拷贝角色",
                "parameters": [
                    {
                        "description": "旧角色id, 新权限id, 新权限名, 新父角色id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.SysAuthorityCopyResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"拷贝成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/createAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "权限id, 权限名, 父角色id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysAuthority"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/deleteAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "删除角色",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysAuthority"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/getAuthorityList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "分页获取角色列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/setDataAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "设置角色资源权限",
                "parameters": [
                    {
                        "description": "设置角色资源权限",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysAuthority"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"设置成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/authority/updateAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authority"
                ],
                "summary": "更新角色信息",
                "parameters": [
                    {
                        "description": "权限id, 权限名, 父角色id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysAuthority"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/autoCode/createTemp": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCode"
                ],
                "summary": "自动代码模板",
                "parameters": [
                    {
                        "description": "创建自动代码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AutoCodeStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/autoCode/getColumn": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCode"
                ],
                "summary": "获取当前表所有字段",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/autoCode/getDatabase": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCode"
                ],
                "summary": "获取当前所有数据库",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/autoCode/getTables": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCode"
                ],
                "summary": "获取当前数据库所有表",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/captcha": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "生成验证码",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"验证码获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/casbin/UpdateCasbin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "更新角色api权限",
                "parameters": [
                    {
                        "description": "权限id, 权限模型列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CasbinInReceive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/casbin/getPolicyPathByAuthorityId": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "获取权限列表",
                "parameters": [
                    {
                        "description": "权限id, 权限模型列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CasbinInReceive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/email/emailTest": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "发送测试邮件",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"发送成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/deleteFile": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "description": "传入文件里面id即可",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExaFileUploadAndDownload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/getFileList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "分页文件列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "上传文件示例",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传文件示例",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"上传成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jwt/jsonInBlacklist": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jwt"
                ],
                "summary": "jwt加入黑名单",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"拉黑成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/GetMenuAuthority": {
=======
        "/k8sDeployments/createK8sDeployment": {
>>>>>>> develop
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "AuthorityMenu"
                ],
                "summary": "获取指定角色menu",
                "parameters": [
                    {
                        "description": "角色ID",
=======
                    "K8sDeployment"
                ],
                "summary": "创建K8sDeployment",
                "parameters": [
                    {
                        "description": "创建K8sDeployment",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.GetAuthorityId"
=======
                            "$ref": "#/definitions/model.K8sDeployment"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/addBaseMenu": {
            "post": {
=======
        "/k8sDeployments/deleteK8sDeployment": {
            "delete": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Menu"
                ],
                "summary": "新增菜单",
                "parameters": [
                    {
                        "description": "路由path, 父菜单ID, 路由name, 对应前端文件路径, 排序标记",
=======
                    "K8sDeployment"
                ],
                "summary": "删除K8sDeployment",
                "parameters": [
                    {
                        "description": "删除K8sDeployment",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysBaseMenu"
=======
                            "$ref": "#/definitions/model.K8sDeployment"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"添加成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/addMenuAuthority": {
            "post": {
=======
        "/k8sDeployments/deleteK8sDeploymentByIds": {
            "delete": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "AuthorityMenu"
                ],
                "summary": "增加menu和角色关联关系",
                "parameters": [
                    {
                        "description": "角色ID",
=======
                    "K8sDeployment"
                ],
                "summary": "批量删除K8sDeployment",
                "parameters": [
                    {
                        "description": "批量删除K8sDeployment",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.AddMenuAuthorityInfo"
=======
                            "$ref": "#/definitions/request.IdsReq"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"添加成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"批量删除成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/deleteBaseMenu": {
            "post": {
=======
        "/k8sDeployments/findK8sDeployment": {
            "get": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Menu"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "description": "菜单id",
=======
                    "K8sDeployment"
                ],
                "summary": "用id查询K8sDeployment",
                "parameters": [
                    {
                        "description": "用id查询K8sDeployment",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.GetById"
=======
                            "$ref": "#/definitions/model.K8sDeployment"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"查询成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/getBaseMenuById": {
            "post": {
=======
        "/k8sDeployments/getK8sDeploymentList": {
            "get": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Menu"
                ],
                "summary": "根据id获取菜单",
                "parameters": [
                    {
                        "description": "菜单id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/menu/getBaseMenuTree": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuthorityMenu"
                ],
                "summary": "获取用户动态路由",
                "parameters": [
                    {
                        "description": "空",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Empty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/menu/getMenu": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuthorityMenu"
                ],
                "summary": "获取用户动态路由",
                "parameters": [
                    {
                        "description": "空",
=======
                    "K8sDeployment"
                ],
                "summary": "分页获取K8sDeployment列表",
                "parameters": [
                    {
                        "description": "分页获取K8sDeployment列表",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.Empty"
=======
                            "$ref": "#/definitions/request.K8sDeploymentSearch"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/getMenuList": {
            "post": {
=======
        "/k8sDeployments/updateK8sDeployment": {
            "put": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Menu"
                ],
                "summary": "分页获取基础menu列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
=======
                    "K8sDeployment"
                ],
                "summary": "更新K8sDeployment",
                "parameters": [
                    {
                        "description": "更新K8sDeployment",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.PageInfo"
=======
                            "$ref": "#/definitions/model.K8sDeployment"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/menu/updateBaseMenu": {
            "post": {
=======
        "/k8sNamespaces/findK8sNamespaces": {
            "get": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "Menu"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "description": "路由path, 父菜单ID, 路由name, 对应前端文件路径, 排序标记",
=======
                    "K8sNamespaces"
                ],
                "summary": "用id查询K8sNamespaces",
                "parameters": [
                    {
                        "description": "用id查询K8sNamespaces",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysBaseMenu"
=======
                            "$ref": "#/definitions/model.K8sNamespaces"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"查询成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionary/createSysDictionary": {
=======
        "/k8sNamespaces/getK8sNamespacesList": {
>>>>>>> develop
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionary"
                ],
                "summary": "创建SysDictionary",
                "parameters": [
                    {
                        "description": "SysDictionary模型",
=======
                    "K8sNamespaces"
                ],
                "summary": "分页获取K8sNamespaces列表",
                "parameters": [
                    {
                        "description": "分页获取K8sNamespaces列表",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionary"
=======
                            "$ref": "#/definitions/request.K8sNamespacesSearch"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"创建成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionary/deleteSysDictionary": {
            "delete": {
=======
        "/menu/GetMenuAuthority": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionary"
                ],
                "summary": "删除SysDictionary",
                "parameters": [
                    {
                        "description": "SysDictionary模型",
=======
                    "AuthorityMenu"
                ],
                "summary": "获取指定角色menu",
                "parameters": [
                    {
                        "description": "角色ID",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionary"
=======
                            "$ref": "#/definitions/request.GetAuthorityId"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionary/findSysDictionary": {
            "get": {
=======
        "/menu/addBaseMenu": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionary"
                ],
                "summary": "用id查询SysDictionary",
                "parameters": [
                    {
                        "description": "ID或字典英名",
=======
                    "Menu"
                ],
                "summary": "新增菜单",
                "parameters": [
                    {
                        "description": "路由path, 父菜单ID, 路由name, 对应前端文件路径, 排序标记",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionary"
=======
                            "$ref": "#/definitions/model.SysBaseMenu"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"查询成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"添加成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionary/getSysDictionaryList": {
            "get": {
=======
        "/menu/addMenuAuthority": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionary"
                ],
                "summary": "分页获取SysDictionary列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小, 搜索条件",
=======
                    "AuthorityMenu"
                ],
                "summary": "增加menu和角色关联关系",
                "parameters": [
                    {
                        "description": "角色ID",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.SysDictionarySearch"
=======
                            "$ref": "#/definitions/request.AddMenuAuthorityInfo"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"添加成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionary/updateSysDictionary": {
            "put": {
=======
        "/menu/deleteBaseMenu": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionary"
                ],
                "summary": "更新SysDictionary",
                "parameters": [
                    {
                        "description": "SysDictionary模型",
=======
                    "Menu"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "description": "菜单id",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionary"
=======
                            "$ref": "#/definitions/request.GetById"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionaryDetail/createSysDictionaryDetail": {
=======
        "/menu/getBaseMenuById": {
>>>>>>> develop
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionaryDetail"
                ],
                "summary": "创建SysDictionaryDetail",
                "parameters": [
                    {
                        "description": "SysDictionaryDetail模型",
=======
                    "Menu"
                ],
                "summary": "根据id获取菜单",
                "parameters": [
                    {
                        "description": "菜单id",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionaryDetail"
=======
                            "$ref": "#/definitions/request.GetById"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"创建成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionaryDetail/deleteSysDictionaryDetail": {
            "delete": {
=======
        "/menu/getBaseMenuTree": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
<<<<<<< HEAD
                "consumes": [
                    "application/json"
                ],
=======
>>>>>>> develop
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionaryDetail"
                ],
                "summary": "删除SysDictionaryDetail",
                "parameters": [
                    {
                        "description": "SysDictionaryDetail模型",
=======
                    "AuthorityMenu"
                ],
                "summary": "获取用户动态路由",
                "parameters": [
                    {
                        "description": "空",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionaryDetail"
=======
                            "$ref": "#/definitions/request.Empty"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionaryDetail/findSysDictionaryDetail": {
            "get": {
=======
        "/menu/getMenu": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
<<<<<<< HEAD
                "consumes": [
                    "application/json"
                ],
=======
>>>>>>> develop
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionaryDetail"
                ],
                "summary": "用id查询SysDictionaryDetail",
                "parameters": [
                    {
                        "description": "用id查询SysDictionaryDetail",
=======
                    "AuthorityMenu"
                ],
                "summary": "获取用户动态路由",
                "parameters": [
                    {
                        "description": "空",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionaryDetail"
=======
                            "$ref": "#/definitions/request.Empty"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"查询成功\"}",
=======
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
>>>>>>> develop
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionaryDetail/getSysDictionaryDetailList": {
            "get": {
=======
        "/menu/getMenuList": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionaryDetail"
                ],
                "summary": "分页获取SysDictionaryDetail列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小, 搜索条件",
=======
                    "Menu"
                ],
                "summary": "分页获取基础menu列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/request.SysDictionaryDetailSearch"
=======
                            "$ref": "#/definitions/request.PageInfo"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/sysDictionaryDetail/updateSysDictionaryDetail": {
            "put": {
=======
        "/menu/updateBaseMenu": {
            "post": {
>>>>>>> develop
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< HEAD
                    "SysDictionaryDetail"
                ],
                "summary": "更新SysDictionaryDetail",
                "parameters": [
                    {
                        "description": "更新SysDictionaryDetail",
=======
                    "Menu"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "description": "路由path, 父菜单ID, 路由name, 对应前端文件路径, 排序标记",
>>>>>>> develop
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< HEAD
                            "$ref": "#/definitions/model.SysDictionaryDetail"
=======
                            "$ref": "#/definitions/model.SysBaseMenu"
>>>>>>> develop
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/ReloadSystem": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "重启系统",
                "parameters": [
                    {
                        "description": "重启系统",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.System"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"重启系统成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/getServerInfo": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取服务器信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/getSystemConfig": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取配置文件内容",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/setSystemConfig": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "设置配置文件内容",
                "parameters": [
                    {
                        "description": "设置配置文件内容",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.System"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"设置成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/changePassword": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "用户名, 原密码, 新密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ChangePasswordStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/deleteUser": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "description": "用户ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetById"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/getUserList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "分页获取用户列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "用户注册账号",
                "parameters": [
                    {
                        "description": "用户名, 昵称, 密码, 角色ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"注册成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/setUserAuthority": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "设置用户权限",
                "parameters": [
                    {
                        "description": "用户UUID, 角色ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SetUserAuth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/setUserInfo": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "设置用户信息",
                "parameters": [
                    {
                        "description": "ID, 用户名, 昵称, 头像链接",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"设置成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.Captcha": {
            "type": "object",
            "properties": {
                "imgHeight": {
                    "type": "integer"
                },
                "imgWidth": {
                    "type": "integer"
                },
                "keyLong": {
                    "type": "integer"
                }
            }
        },
        "config.Casbin": {
            "type": "object",
            "properties": {
                "modelPath": {
                    "type": "string"
                }
            }
        },
        "config.Email": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "isSSL": {
                    "type": "boolean"
                },
                "nickname": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "config.JWT": {
            "type": "object",
            "properties": {
                "signingKey": {
                    "type": "string"
                }
            }
        },
        "config.Local": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "config.Mysql": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "string"
                },
                "dbname": {
                    "type": "string"
                },
                "logMode": {
                    "type": "boolean"
                },
                "logZap": {
                    "type": "string"
                },
                "maxIdleConns": {
                    "type": "integer"
                },
                "maxOpenConns": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "config.Qiniu": {
            "type": "object",
            "properties": {
                "accessKey": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string"
                },
                "imgPath": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                },
                "useCdnDomains": {
                    "type": "boolean"
                },
                "useHttps": {
                    "type": "boolean"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "config.Redis": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "db": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "config.Server": {
            "type": "object",
            "properties": {
                "captcha": {
                    "$ref": "#/definitions/config.Captcha"
                },
                "casbin": {
                    "$ref": "#/definitions/config.Casbin"
                },
                "email": {
                    "$ref": "#/definitions/config.Email"
                },
                "jwt": {
                    "$ref": "#/definitions/config.JWT"
                },
                "local": {
                    "description": "oss",
                    "$ref": "#/definitions/config.Local"
                },
                "mysql": {
                    "description": "gorm",
                    "$ref": "#/definitions/config.Mysql"
                },
                "qiniu": {
                    "$ref": "#/definitions/config.Qiniu"
                },
                "redis": {
                    "$ref": "#/definitions/config.Redis"
                },
                "system": {
                    "$ref": "#/definitions/config.System"
                },
                "zap": {
                    "$ref": "#/definitions/config.Zap"
                }
            }
        },
        "config.System": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "integer"
                },
                "dbType": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "ossType": {
                    "type": "string"
                },
                "useMultipoint": {
                    "type": "boolean"
                }
            }
        },
        "config.Zap": {
            "type": "object",
            "properties": {
                "director": {
                    "type": "string"
                },
                "encodeLevel": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "linkName": {
                    "type": "string"
                },
                "logInConsole": {
                    "type": "boolean"
                },
                "prefix": {
                    "type": "string"
                },
                "showLine": {
                    "type": "boolean"
                },
                "stacktraceKey": {
                    "type": "string"
                }
            }
        },
        "model.AutoCodeStruct": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "autoCreateApiToSql": {
                    "type": "boolean"
                },
                "autoMoveFile": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Field"
                    }
                },
                "packageName": {
                    "type": "string"
                },
                "structName": {
                    "type": "string"
                },
                "tableName": {
                    "type": "string"
                }
            }
        },
        "model.ExaFileUploadAndDownload": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.Field": {
            "type": "object",
            "properties": {
                "columnName": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "dataType": {
                    "type": "string"
                },
                "dataTypeLong": {
                    "type": "string"
                },
                "dictType": {
                    "type": "string"
                },
                "fieldDesc": {
                    "type": "string"
                },
                "fieldJson": {
                    "type": "string"
                },
                "fieldName": {
                    "type": "string"
                },
                "fieldSearchType": {
                    "type": "string"
                },
                "fieldType": {
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
=======
        "model.K8sDeployment": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deployment": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "namespace": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.K8sNamespaces": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "namespace": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
>>>>>>> develop
        "model.SysApi": {
            "type": "object",
            "properties": {
                "apiGroup": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SysAuthority": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "authorityName": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysAuthority"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "dataAuthorityId": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysAuthority"
                    }
                },
                "deletedAt": {
                    "type": "string"
                },
                "menus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysBaseMenu"
                    }
                },
                "parentId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SysBaseMenu": {
            "type": "object",
            "properties": {
                "authoritys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysAuthority"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysBaseMenu"
                    }
                },
                "component": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "defaultMenu": {
                    "type": "boolean"
                },
                "hidden": {
                    "type": "boolean"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keepAlive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysBaseMenuParameter"
                    }
                },
                "parentId": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SysBaseMenuParameter": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "sysBaseMenuID": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
        "model.SysDictionary": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "sysDictionaryDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysDictionaryDetail"
                    }
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SysDictionaryDetail": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "sysDictionaryID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
=======
>>>>>>> develop
        "model.SysUser": {
            "type": "object",
            "properties": {
                "authority": {
                    "$ref": "#/definitions/model.SysAuthority"
                },
                "authorityId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "headerImg": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.System": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/config.Server"
                }
            }
        },
        "request.AddMenuAuthorityInfo": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "menus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysBaseMenu"
                    }
                }
            }
        },
        "request.CasbinInReceive": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "casbinInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.CasbinInfo"
                    }
                }
            }
        },
        "request.CasbinInfo": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.ChangePasswordStruct": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.Empty": {
            "type": "object"
        },
        "request.GetAuthorityId": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                }
            }
        },
        "request.GetById": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number"
                }
            }
        },
<<<<<<< HEAD
        "request.Login": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captchaId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "request.SearchApiParams": {
            "type": "object",
            "properties": {
                "apiGroup": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "boolean"
                },
                "description": {
=======
        "request.IdsReq": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "request.K8sDeploymentSearch": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deployment": {
>>>>>>> develop
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "method": {
                    "type": "string"
                },
                "orderKey": {
=======
                "namespace": {
>>>>>>> develop
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "path": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "request.SetUserAuth": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "uuid": {
=======
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "updatedAt": {
>>>>>>> develop
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
        "request.SysDictionaryDetailSearch": {
=======
        "request.K8sNamespacesSearch": {
>>>>>>> develop
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "label": {
=======
                "namespace": {
>>>>>>> develop
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "sysDictionaryID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
=======
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captchaId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
>>>>>>> develop
                    "type": "integer"
                }
            }
        },
<<<<<<< HEAD
        "request.SysDictionarySearch": {
            "type": "object",
            "properties": {
=======
        "request.SearchApiParams": {
            "type": "object",
            "properties": {
                "apiGroup": {
                    "type": "string"
                },
>>>>>>> develop
                "createdAt": {
                    "type": "string"
                },
                "desc": {
<<<<<<< HEAD
=======
                    "type": "boolean"
                },
                "description": {
>>>>>>> develop
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "name": {
=======
                "method": {
                    "type": "string"
                },
                "orderKey": {
>>>>>>> develop
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
<<<<<<< HEAD
                "status": {
                    "type": "boolean"
                },
                "sysDictionaryDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SysDictionaryDetail"
                    }
                },
                "type": {
=======
                "path": {
>>>>>>> develop
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
<<<<<<< HEAD
=======
        "request.SetUserAuth": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
>>>>>>> develop
        "response.SysAuthorityCopyResponse": {
            "type": "object",
            "properties": {
                "authority": {
                    "$ref": "#/definitions/model.SysAuthority"
                },
                "oldAuthorityId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample Server pets",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
